### ISSUE TITLE
Alternative to loading resources from classpath

### ISSUE THREAD

**Issue by schildbach** [JodaOrg/joda-money#27]
I'm evaluating the use of joda-money in the Android app Bitcoin Wallet (https://github.com/schildbach/bitcoin-wallet).

However, Android does not support classpath resources. You usually store files like that in assets. Some static initialization method like 

Yoda.initFrom("assets/MoneyData.csv")

would do.

**Comment by cs-victor-nascimento** [comment]
Since this issue is the second result in a Google search for "Joda-money Android" today, I've done some measurements with the help of @cs-rafael-toledo to check what would be the performance cost of using Joda-money or a custom fork that avoids the static block initialization and loads the CSV from assets instead of the classpath resource. 

We've tried a simple setup ranging from Android API versions 10 to 24 and detected that the cost is marginally around few tenths of milliseconds. Plenty of times there is no penalty at all. So, our conclusion is that joda-money is safe to use as is in an Android application without significant performance costs.

We hope this proves useful for future reference.
