### ISSUE TITLE
Support Indian Lakh/Crore format

### ISSUE THREAD

**Issue by jodastephen** [JodaOrg/joda-money#58]
Add "extended grouping size" to `MoneyAmountStyle`. Matches design used in other systems.

**Comment by jodastephen** [comment]
MoneyFormatter formatter = new MoneyFormatterBuilder()
      .appendAmount(
          MoneyAmountStyle.ASCII_DECIMAL_POINT_GROUP3_COMMA
              .withExtendedGroupingSize(2))
      .toFormatter();

**Comment by dmytrodruppov** [comment]
Hello jodastephen, 

Can joda money support the below formats for Indian figures?
There is probably an issue, because not only the nearest group to decimal point has 3 digits.
If there is a possibility to get the results below with Joda library I will be really appreciate you.

The below are correct formats for Indian Rupees. (https://en.wikipedia.org/wiki/Indian_numbering_system)

1,00,00,000,00,00,000 
10,00,00,000,00,00,000
100,00,00,000,00,00,000 | 
1,000,00,00,000,00,00,000
10,000,00,00,000,00,00,000

**Comment by jodastephen** [comment]
The change linked to this issue allows for 3 digits next to the decimal point and 2 digits beyond that. For numbers up to 99,99,99,999 that matches the Indian system. A pull request to handle bigger numbers could be discussed if desired.

**Comment by dmytrodruppov** [comment]
Yes, this feature will be quite desirable for our project, ICU4J also not supports that feature. 
If this will be possible, could please tell when it might be potentially released? Thank you!

**Comment by jodastephen** [comment]
I have no plans to work on this. If you want to raise a PR, you are free to do so. I think the best API would be an extra argument to `withExtendedGroupingSize(int groupingSize, int repetition)`, where `withExtendedGroupingSize(2, 3)` would create the Indian system. (`repetition` being the number of groups before the pattern repeats)
