### ISSUE TITLE
Include support for all currencies in ISO4217

### ISSUE THREAD

**Issue by PeddyOfficer** [JodaOrg/joda-money#64]
Hi.

It would be better if all currencies in ISO4217 were included in org/joda/money/MoneyData.csv instead of having to have a separate list for some ISO4217 currencies in org/joda/money/MoneyDataExtension.csv.

Some currencies are quite "exotic" but are used in payment applications.

Regards, 
Roger

**Comment by davidkarlsen** [comment]
Examples are inclusion of the USN, and USS: https://en.wikipedia.org/wiki/ISO_4217

**Comment by jodastephen** [comment]
I started having a go at this, but it turned out to be a much bigger and more fiddly task than expected
https://github.com/JodaOrg/joda-money/commit/31eafdb65146971a3f2f90b9a56d37d8c951d6d8

Not sure when I'll get the time to finish it, but I'm open to PRs or a second pair of eyes checking what I've done.
